[project]
name = "dina.matcher"
version = "1.0.0-beta.2"
description = "Add your description here"
readme = "README.md"
license = "MIT OR Apache-2.0"
authors = [
    { name = "Mark Giraud", email = "mark.giraud@iosb.fraunhofer.de" }
]
requires-python = ">=3.13,<3.14"

dependencies = [
    "aiohttp>=3.12.13",
    "asyncpg>=0.29.0",
    "colorlog>=6.9.0",
    "dotenv>=0.9.9",
    "fastapi>=0.116.1",
    "hatchling>=1.27.0",
    "httpx",
    "lazy-imports",
    "mypy>=1.16.1",
    "numpy>=1.26.0",
    "openapi-python-client",
    "packaging>=24.1",
    "polars>=0.20.30",
    "psycopg[binary]>=3.2.9",
    "pydantic>=2.11.7",
    "pyjwt>=2.10.1",
    "pwdlib[argon2]>=0.3.0",
    "python-dateutil",
    "python-multipart>=0.0.20",
    "rapidfuzz>=3.9.7",
    "sqlalchemy[asyncio]>=2.0.0",
    "uvicorn>=0.35.0",
]

[project.optional-dependencies]
netbox_fetcher = ["dina.plugins.datasource.netbox_fetcher"]
isduba_fetcher = ["dina.plugins.datasource.isduba_fetcher"]
sample = ["dina.plugins.datasource.sample"]
preprocessing-identity = ["dina.plugins.preprocessing.identity"]
preprocessing-default = ["dina.plugins.preprocessing.default"]

[project.scripts]
assetsync = "dina.assetsync.main:main"
csafsync = "dina.csafsync.main:main"
csaf_matcher = "dina.matcher.main:main"
csaf_matcher_cli = "dina.cli.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/dina"]

[tool.uv.workspace]
members = [
    "plugins/asset_source/isduba",
    "plugins/asset_source/netbox",
    "plugins/asset_source/sample",
    "plugins/preprocessing/identity",
    "plugins/preprocessing/default"
]

[tool.uv.sources]
"dina.plugins.datasource.netbox_fetcher" = { workspace = true }
"dina.plugins.datasource.isduba_fetcher" = { workspace = true }
dina-plugins-datasource-sample = { workspace = true }
dina-plugins-preprocessing-identity = { workspace = true }
dina-plugins-preprocessing-default = { workspace = true }

[tool.ruff]
exclude = [
    "plugins/asset_source/netbox/src/dina/plugins/datasource/netbox/api_client",
    "dev"
]
respect-gitignore = true

[tool.pytest.ini_options]
testpaths = [
    "tests",
    "plugins/asset_source/*/tests",
    "plugins/preprocessing/*/tests"
]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
markers = [
    "asyncio: mark a test as using asyncio"
]
addopts = [
    "--strict-markers",
    "--strict-config",
    "--cov=src",
    "--cov-report=html",
    "--cov-report=term-missing"
]
asyncio_mode = "auto"
filterwarnings = [
    "ignore::DeprecationWarning:testcontainers.*:",
    "ignore::DeprecationWarning:sqlalchemy.*:",
    "ignore::UserWarning"
]

[tool.coverage.run]
omit = [
    "plugins/asset_source/netbox/src/dina/plugins/datasource/netbox/generated/*",
    "plugins/asset_source/isduba/src/dina/plugins/datasource/isduba/generated/*",
]

[tool.coverage.report]
exclude_also = [
    # Don't complain about missing debug-only code:
    "def __repr__",
    "if self\\.debug",

    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",

    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if __name__ == .__main__.:",

    # Don't complain about abstract methods, they aren't run:
    "@(abc\\.)?abstractmethod",
]

[dependency-groups]
dev = [
    "furo>=2024.8.6",
    "line-profiler",
    "locust>=2.0.0",
    "matplotlib",
    "mypy>=1.16.0",
    "pre-commit>=4.2.0",
    "psutil",
    "pyinstrument",
    "pytest>=8.4.1",
    "pytest-asyncio>=0.25.0",
    "pytest-benchmark",
    "pytest-cov>=6.2.1",
    "ruff>=0.12.0",
    "sphinx>=7.3.7",
    "sphinxcontrib-programoutput",
    "testcontainers>=4.8.2",
]
